[package]
name = "spatialmap"
version = "0.2.3"
edition = "2024"

[dependencies]
glam = { version = "0.27.0", optional = true }

#[profile.dev]
#strip = false
#debug = true
#
#[profile.release]
#strip = false
#debug = true
#lto = "fat"
##opt-level = 3 # change to 3 when building for real