[package]
name = "spatialmap"
version = "0.2.0"
edition = "2024"

[dependencies]

#[profile.dev]
#strip = false
#debug = true
#
#[profile.release]
#strip = false
#debug = true
#lto = "fat"
##opt-level = 3 # change to 3 when building for real